const ERROR_MESSAGES: Record<string, string> = {
  DB_ERROR: "操作失败，请稍后重试。",
  GITHUB_ERROR: "与 GitHub 通信时发生错误。",
  FS_ERROR: "读取文件系统时发生错误。",
  LOCAL_DISABLED: "本服务器未启用本地模式。",
  PATH_NOT_FOUND:
    "此路径在服务器上不存在。本地文件夹功能需要 self-hosted 部署。",
  PATH_STALE: "此本地文件夹已不存在或已被移动。",
  REGISTRATION_DISABLED: "此服务器已禁用注册。",
  WORKSPACE_ERROR: "工作空间操作失败，请稍后重试。",
  PROJECT_LIMIT_EXCEEDED: "活跃项目数已达上限，请先归档已完成的项目，或升级套餐。",
  INVITATION_ERROR: "邀请操作失败，请稍后重试。",
  MEMBER_ALREADY_EXISTS: "该用户已经是此工作空间的成员。",
  INVITATION_EXPIRED: "邀请已过期，请联系管理员重新发送邀请。",
  INVITATION_INVALID: "邀请链接无效或已被使用。",
  CANNOT_REMOVE_SOLE_OWNER: "无法移除唯一的 Owner，请先转移所有权。",
  MEMBER_ERROR: "成员操作失败，请稍后重试。",
  SELF_REMOVE_NOT_ALLOWED: "不能将自己从工作空间移除。",
  ROLE_UPDATE_ERROR: "角色更新失败，请稍后重试。",
  CANNOT_ASSIGN_OWNER_ROLE: "只有 Owner 可以赋予其他成员 Owner 角色。",
  CANNOT_CHANGE_OWN_ROLE: "不能修改自己的角色，请联系其他管理员操作。",
  SETTINGS_READ_ERROR: "治理策略读取失败，请稍后重试。",
  SETTINGS_UPDATE_ERROR: "治理策略更新失败，请稍后重试。",
  TEAM_WORKSPACE_REQUIRED: "执行策略配置仅适用于团队工作空间。",
  PROJECT_IMPORT_ERROR: "项目导入失败，请稍后重试。",
  REPO_NOT_FOUND: "找不到指定的仓库记录。",
  WORKSPACE_ACCESS_DENIED: "您没有访问此工作空间的权限。",
  PROJECT_ACCESS_DENIED: "您没有访问此项目的权限。",
  INSUFFICIENT_PERMISSION: "您的角色权限不足，无法执行此操作。",
  VALIDATION_ERROR: "输入参数无效。",
  UNAUTHORIZED: "未登录，请先登录。",
  TOKEN_MISSING: "未找到 GitHub OAuth 令牌，请重新连接。",
  ARTIFACT_SCAN_ERROR: "工件扫描失败，请检查仓库连接后重试。",
  ARTIFACT_SYNC_ERROR: "工件同步失败，请稍后重试。",
  ARTIFACT_NOT_FOUND: "找不到指定的工件记录。",
  REPO_NOT_LINKED: "项目未关联仓库，无法执行工件扫描。",
  TASK_CREATION_ERROR: "任务创建失败，请稍后重试。",
  TASK_NOT_FOUND: "找不到指定的任务记录。",
  TASK_DISPATCH_ERROR: "任务派发失败，请稍后重试。",
  TASK_DISPATCH_NOT_READY: "当前任务还不能执行首次派发。",
  TASK_ALREADY_DISPATCHED: "任务已经完成派发，无需重复操作。",
  TASK_AGENT_SELECTION_REQUIRED: "当前工作空间要求先指定 Agent，系统不会自动派发。",
  TASK_REDISPATCH_ERROR: "任务重新派发失败，请稍后重试。",
  TASK_REDISPATCH_NOT_AVAILABLE: "当前任务还没有可重新派发的 Agent Run。",
  TASK_REDISPATCH_CONFLICT: "任务的当前 Agent Run 已发生变化，请刷新详情后再试。",
  TASK_REDISPATCH_NOOP: "目标 Agent 与当前 Agent 相同，无需重复改派。",
  TASK_RUNNING_REDISPATCH_CONFIRMATION_REQUIRED: "当前任务正在执行。请确认终止当前执行后再重新派发。",
  TASK_RUNNING_REDISPATCH_PRECONDITION_MISSING: "当前运行会话缺少可安全终止的执行句柄，暂时不能重新派发。",
  EXECUTION_SESSION_TERMINATION_UNAVAILABLE: "当前运行会话暂不支持安全终止，请稍后重试或等待执行监督器接入。",
  TMUX_NOT_AVAILABLE: "tmux 不可用，请确认系统已安装 tmux。",
  EXECUTION_NO_LOCAL_REPO: "当前项目还没有可用于 self-hosted 执行的本地目录。",
  TASK_LAUNCH_NO_RUN: "当前任务没有可启动的 Agent Run。",
  TASK_LAUNCH_RUN_MISMATCH: "Agent Run 与当前任务不匹配，请刷新后重试。",
  TASK_LAUNCH_NOT_DISPATCHED: "当前任务状态还不能启动执行会话。",
  TASK_LAUNCH_ALREADY_STARTED: "该 Agent Run 已经启动过了。",
  TASK_LAUNCH_SESSION_EXISTS: "该 Agent Run 已有活跃执行会话。",
  TASK_LAUNCH_RACE_CONDITION: "任务状态已被其他操作改变，请刷新后重试。",
  TASK_LAUNCH_COMMIT_FAILED: "执行会话启动失败，请稍后重试。",
  EXECUTION_START_ERROR: "启动执行会话失败，请稍后重试。",
  WRITEBACK_ERROR: "执行结果回写失败，请稍后重试。",
  WRITEBACK_INVALID_STATE: "当前任务状态还不能回写执行结果。",
  ARTIFACT_CONTEXT_ERROR: "工件上下文构建失败，请检查工件内容后重试。",
  ARTIFACT_SOURCE_NOT_FOUND: "找不到指定的来源工件。",
  ARTIFACT_SOURCE_UNREADABLE: "来源工件无法读取，请检查仓库连接或本地目录配置。",
  PLANNING_REQUEST_CREATE_ERROR: "规划请求创建失败，请稍后重试。",
  PLANNING_REQUEST_NOT_FOUND: "找不到指定的规划请求记录。",
  PLANNING_REQUEST_ANALYZE_ERROR: "规划意图分析失败，请稍后重试。",
  PLANNING_REQUEST_LIST_ERROR: "规划请求读取失败，请稍后重试。",
  PLANNING_REQUEST_DETAIL_ERROR: "规划链路详情加载失败，请稍后重试。",
  PLANNING_REQUEST_EXECUTE_ERROR: "规划执行失败，请稍后重试。",
  PLANNING_REQUEST_EXECUTION_NOT_READY: "当前规划请求还未准备好执行，请先完成分析后再试。",
  PLANNING_REQUEST_EXECUTION_UNSUPPORTED: "该规划请求不属于 BMAD 规划链路，当前不能执行规划工件生成。",
  PLANNING_REQUEST_RETRY_NOT_AVAILABLE: "当前没有可重试的失败步骤。",
  PLANNING_REQUEST_CONFIRM_ERROR: "规划确认失败，请稍后重试。",
  PLANNING_REQUEST_CONFIRMATION_NOT_READY: "当前规划请求还不能执行确认，请先完成规划生成。",
  PLANNING_REQUEST_CONFIRMATION_UNSUPPORTED: "该请求不属于可确认的规划衔接链路。",
  PLANNING_REQUEST_CONFIRMATION_INVALID_SELECTION: "确认选择无效，请刷新后重试。",
  PLANNING_REQUEST_NO_EXECUTABLE_TASKS: "当前规划产出尚未形成可执行任务条目。",
  PLANNING_REQUEST_HANDOFF_PREVIEW_ERROR: "规划衔接预览加载失败，请稍后重试。",
  PLANNING_REPO_REQUIRED: "当前项目尚未关联仓库，无法生成规划工件。请先关联仓库后重试。",
  PLANNING_SKILL_UNSUPPORTED: "当前规划请求包含暂不支持的 Skill，无法继续执行。",
  PLANNING_ARTIFACT_WRITE_ERROR: "规划工件写入失败，请检查仓库连接或本地目录权限后重试。",
  PLANNING_ARTIFACT_CONFLICT: "检测到现有工件与自动投影内容冲突，已停止覆盖并保留现有文件。",
  PLANNING_REQUEST_GOAL_REQUIRED: "请输入明确的目标描述，不能只包含空格或标点。",
  PLANNING_REQUEST_GOAL_TOO_SHORT: "请至少输入 6 个字符，说明希望系统规划的目标。",
  PLANNING_REQUEST_GOAL_TOO_LONG: "目标描述请控制在 500 个字符以内。",
  ADMISSION_TASK_NOT_FOUND: "找不到指定的任务记录。",
  ADMISSION_NO_RUN: "当前任务还没有可启动的 Agent Run。",
  ADMISSION_NOT_DISPATCHED: "当前任务状态还不能启动执行会话。",
  ADMISSION_CAPACITY_FULL: "工作空间并发上限已满，任务已排入等待队列。",
  EXECUTION_BOUNDARY_ROOT_UNAVAILABLE: "项目执行根目录不可用或无法访问。",
  EXECUTION_BOUNDARY_ROOT_IS_SYMLINK: "项目根目录本身是符号链接，不允许作为执行根目录。",
  EXECUTION_BOUNDARY_SCOPE_MISMATCH: "执行作用域与任务上下文不匹配。",
  EXECUTION_BOUNDARY_PATH_TRAVERSAL: "检测到路径穿越尝试，已被系统拦截。",
  EXECUTION_BOUNDARY_SYMLINK_BLOCKED: "符号链接访问被系统拒绝。",
  EXECUTION_BOUNDARY_SENSITIVE_PATH_BLOCKED: "敏感文件访问被系统跳过。",
  EXECUTION_CONTEXT_PREPARATION_FAILED: "执行上下文准备失败，请稍后重试。",
  EXECUTION_CONTEXT_LIMIT_EXCEEDED: "执行上下文规模超出系统限制。",
};

export function sanitizeError(error: unknown, code: string): string {
  console.error(`[${code}]`, error);
  return ERROR_MESSAGES[code] ?? "发生了意外错误，请稍后重试。";
}
